const ActionTypes =
{
    RESET: 'RESET',
    SET_LOADING: 'SET_LOADING',
    SET_VERIFIED: 'SET_VERIFIED',
    SET_ADMIN: 'SET_ADMIN',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_PRODUCT: 'SET_PRODUCT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    SET_TAGS: 'SET_TAGS',
    ADD_TAG: 'ADD_TAG',
    REMOVE_TAG: 'REMOVE_TAG',
    SET_USERS_WITH_RIGHTS: 'SET_USERS_WITH_RIGHTS',
    SET_USER_VERIFIED: 'SET_USER_VERIFIED',
    SET_CART: 'SET_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
    SET_CART_ITEM: 'SET_CART_ITEM',
    SET_ORDERS: 'SET_ORDERS',
    SET_ORDER_COMPLETED: 'SET_ORDER_COMPLETED'
}

export default ActionTypes