const ActionTypes =
{
    RESET: 'RESET',
    SET_LOADING: 'SET_LOADING',
    SET_VERIFIED: 'SET_VERIFIED',
    SET_ADMIN: 'SET_ADMIN',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_PRODUCT: 'SET_PRODUCT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    SET_TAGS: 'SET_TAGS',
    ADD_TAG: 'ADD_TAG',
    REMOVE_TAG: 'REMOVE_TAG',
    SET_USERS_WITH_RIGHTS: 'SET_USERS_WITH_RIGHTS'
}

export default ActionTypes